---
- hosts: web
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present
    - name: create index.html
      template:
         src: /opt/ansible-lab/examples/templates/index.html.j2
         dest: /var/www/html/index.html
      notify: restart_httpd
    - name: start and enable httpd
      service:
        name: httpd
        state: started
        enabled: true
    - name: check home page
      uri:
        url: "http://{{ item }}"
      with_items: "{{ groups['web'] }}"
      delegate_to: localhost
      run_once: true

  handlers:
    - name: restart_httpd
      service:
        name: httpd
        state: restarted
