version: "2"

volumes:
  ansible_vol:

services:
  base:
    build:
      context: ./base/
      args:
        - http_proxy
        - https_proxy
    image: ansible_base
    command: /bin/true
  master:
    links:
      - base
    build:
      context: ./master/
      args:
        - http_proxy
        - https_proxy
    image: ansible_master
    container_name: master01
    restart: always
    hostname: master01
    ports:
      - "2022:22"
    volumes:
      - ansible_vol:/opt/ansible-lab
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
  host:
    links:
      - base
      - master
    build:
      context: ./host/
      args:
        - http_proxy
        - https_proxy
    image: ansible_host
    container_name: host01
    restart: always
    hostname: host01
    ports:
      - "8001:80"
    volumes:
      - ansible_vol:/opt/ansible-lab
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    environment:
      - http_proxy
      - https_proxy
    privileged: true
  host02:
    links:
      - base
      - master
      - host
    image: ansible_host
    container_name: host02
    restart: always
    hostname: host02
    ports:
      - "8002:80"
    volumes:
      - ansible_vol:/opt/ansible-lab
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    environment:
      - http_proxy
      - https_proxy
    privileged: true
  host03:
    links:
      - base
      - master
      - host
    image: ansible_host
    container_name: host03
    restart: always
    hostname: host03
    ports:
      - "8003:80"
    volumes:
      - ansible_vol:/opt/ansible-lab
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    environment:
      - http_proxy
      - https_proxy
    privileged: true
