version: "2"

volumes:
  ansible_vol:

services:
  base:
    build: 
      context: ./base/
#      args:
#        http_proxy: myproxy:port
#        https_proxy: myproxy:port
    image: ansible_base
  master:
    links:
      - base
    build: 
      context: ./master/
#      args:
#        http_proxy: myproxy:port
#        https_proxy: myproxy:port
    image: ansible_master
    container_name: master01
    restart: always
    hostname: master01
    command: ["/usr/sbin/sshd","-D"]
    ports:
      - "1022:22"
    volumes:
      - ansible_vol:/opt/ansible-lab
  host:
    links:
      - base
      - master
    build:
      context: ./host/
#      args:
#        http_proxy: myproxy:port
#        https_proxy: myproxy:port
    image: ansible_host
    container_name: host01
    restart: always
    hostname: host01
    command: ["/run.sh"]
    volumes:
      - ansible_vol:/opt/ansible-lab
  host02:
    links:
      - base
      - master
      - host
    image: ansible_host
    container_name: host02
    restart: always
    hostname: host02
    command: ["/run.sh"]
    volumes:
      - ansible_vol:/opt/ansible-lab
  host03:
    links:
      - base
      - master
      - host
    image: ansible_host
    container_name: host03
    restart: always
    hostname: host03
    command: ["/run.sh"]
    volumes:
      - ansible_vol:/opt/ansible-lab

